### ISSUE TITLE
filealreadyexist exception when run on quarkus guides

### ISSUE THREAD

**Issue by maxandersen** [LightGuard/asciidoc-splitter#6]
i assume quarkus current guides breaks some assumptions but might be good to handle the error better.

here is what happens when run on quarkus/asciidoc guides

```
 java -jar ~/code/work/asciidoc-splitter/target/asciidoc-splitter-1.0-SNAPSHOT.jar -s . -o ../result
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/Users/max/code/work/asciidoc-splitter/target/asciidoc-splitter-1.0-SNAPSHOT.jar) to method sun.nio.ch.NativeThread.signal(long)
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.lang.RuntimeException: java.nio.file.FileAlreadyExistsException: /Users/max/code/work/quarkus/quarkus/docs/src/main/asciidoc/../result/modules/native-limitations.adoc
	at com.redhat.documentation.asciidoc.cli.ExtractionRunner.writeModules(ExtractionRunner.java:155)
	at com.redhat.documentation.asciidoc.cli.ExtractionRunner.call(ExtractionRunner.java:75)
	at com.redhat.documentation.asciidoc.cli.ExtractionRunner.call(ExtractionRunner.java:38)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at com.redhat.documentation.asciidoc.cli.ExtractionRunner.main(ExtractionRunner.java:56)
Caused by: java.nio.file.FileAlreadyExistsException: /Users/max/code/work/quarkus/quarkus/docs/src/main/asciidoc/../result/modules/native-limitations.adoc
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:94)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:215)
	at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
	at java.base/java.nio.file.Files.createFile(Files.java:647)
	at com.redhat.documentation.asciidoc.cli.ExtractionRunner.writeModules(ExtractionRunner.java:124)
	... 10 more
```

﻿

**Comment by LightGuard** [comment]
Is this actually the same content, or similar but with the same id?

**Comment by maxandersen** [comment]
Im not sure. Needs further investigation
